@startuml
'https://plantuml.com/sequence-diagram

autonumber

'VRChat TLP structure
control UDON order -10000
control DirectInput order -1000
control Default order 0
control VehicleMotion order 1000
control PlayerMotion order 2000
control Weapons order 3000
control UI order 10000
control Audio order 11000

rnote over DirectInput: -1000 - 0
/ rnote over Default: 0
/ rnote over VehicleMotion: 1000 - 2000
/ rnote over PlayerMotion: 2000 - 3000
/ rnote over Weapons: 3000 - 4000
/ rnote over UI: 10000 - 11000
/ rnote over Audio: 11000 - 12000

'UdonUtils
'-------------
group Udon Utils

    'Order
    '-----
    'UDON
    participant TLPLogger order -10000
    
    'Input
    participant UdonInput order -500
    
    'Weapons
    participant TrackingDataFollower order 3750
    
    'UI
    participant TrackingDataFollowerUI order 10100
    participant LookAtPlayerUI order 10101
    participant DistanceScalerUI order 10102

    'Comments
    '--------
    rnote over TrackingDataFollower: 3750
    / rnote over TLPLogger: -10000
    / rnote over UdonInput: -500
    / rnote over TrackingDataFollowerUI: 10100
    / rnote over LookAtPlayerUI: 10101
    / rnote over DistanceScalerUI: 10102
end

@enduml